### PR TITLE
Andy

### PR DESCRIPTION
**Pull request by birisora**
Added in the project's logo.
Separated the index page into 3 sections if that was needed.
Played around some more with the js,html,css

### CODE REVIEW

**Comment by EthanShimooka** [comment]
hey andy, what file did you modify to get the 3 frames?

**Comment by birisora** [comment]
Oh the file I modified for the three frames is in the index.html

**Comment by EthanShimooka** [comment]
Ok. Are we planning on redoing the Navbar? I was messing around with the Layout and Web2py CSS but I couldn't find where to modify it

**Comment by birisora** [comment]
Probably will redo NavBar, it seems to be called in layout.html, web2py_bootstrap_nojs.css, web2py_bootstrap.css, and web2py.css.

To add more things onto that navbar is through the menu.py, similar to what John did for the About.

**Pull request merged**
